future: true
permalink: /:title/
url: http://mcmicahelchan.github.io
name: Michael Chan
author: Michael Chan
qq: 623769018
email: michaelchan.sysu@gmail.com

duoshuo: yourname
beian: 
cnzz: 
weibo: 
github: mcmicahelchan
about: "这里是 Your 的个人博客，创建于 2018 年。"

safe: true
paginate: 20
